language: node_js
after_success:
  - npm run report
node_js:
  - '6'
  - '8'
jobs:
  include:
    - stage: deploy
      node_js: '8'
      services:
        - docker
      script: skip
      deploy:
        provider: script
        script: bash docker-deploy.sh
        on:
          branch: master
